get http://localhost:4000

###

post http://localhost:4000/users/Register
Content-Type: application/json

{
        "Fac_ID":232903,
        "Fac_Name":"deepak",
        "Department":"Prof of Commerce",
        "Phone_no":7292098071,
        "courses":"BCA",
        "Email":"deepaknegi@gmail.com",
        "Password":"Deepak123"
}

###

post http://localhost:4000/users/Login
Content-Type: application/json 

{
        "Fac_ID":2032903,
        "Email":"ayushdeep@gmail.com",
        "Password":"Deepak123"
}

###

post http://localhost:4000/addstudent
Content-Type: application/json

{
        "Fac_ID":20329038,
        "Sname":"Deep",
        "Course":"BCA",
        "Enroll_no":"01702020",
        "Attendance": "Stable"
}

###

get http://localhost:4000/getstudent
Content-Type: application/json

{
        "Fac_ID":20329038
}

###

post http://localhost:4000/update
Content-Type: application/json

{
        "Enroll_no":"01702020",
        "Attendance":"Present"
}

###

post http://localhost:4000/users/courses
Content-Type: application/json

{
        "Enroll_no":"2032903",
        "courses":"BBA"
}